---
- name: Example Playbook for voraus IPC Tools
  hosts: all
  become: true
  roles:
    - voraus.ipc_tools.realtime_kernel
    - voraus.ipc_tools.core_isolation
    - voraus.ipc_tools.wibu_codemeter
    - geerlingguy.docker
  tasks:
    - name: Install base packages
      ansible.builtin.package:
        name:
          - sudo
          - htop
          - ncdu
          - zip
          - unzip
          - curl
          - wget
          - less
          - nano
          - gnupg2
          - nmap
          - tcpdump
        state: latest
