---
wibu_packages_install:
  codemeter-lite: 8.20.6539.500
  axprotector: 11.70.7131.502

wibu_packages_cm_service_name: codemeter.service
wibu_packages_cm_config_path: /etc/wibu/CodeMeter/Server.ini
wibu_packages_cm_is_network_server: true
wibu_packages_cm_bind_address: '0.0.0.0'
