---
- name: Install dependencies
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - libusb-1.0-0
      - gnupg2
    state: present

- name: Install codemeter in the requested version
  ansible.builtin.apt:
    name: "{{ package_name }}{{ ('=' + package_version) if package_version else '' }}"
    state: present
    allow_downgrade: '{{ wibu_packages_allow_downgrades }}'
  notify:
    - Stop CodeMeter Systemd Service

- name: Force all notified handlers to run at this point (Stop systemd service now)
  ansible.builtin.meta: flush_handlers

- name: Configure License Server
  community.general.ini_file:
    path: '{{ wibu_packages_cm_config_path }}'
    create: false
    section: '{{ item.section }}'
    option: '{{ item.option }}'
    value: '{{ item.value }}'
    ignore_spaces: true
    owner: daemon
    group: daemon
    mode: '0644'
  with_items:
    - section: General
      option: IsNetworkServer
      value: "{{ '1' if wibu_packages_cm_is_network_server else '0' }}"
    - section: General
      option: BindAddress
      value: '{{ wibu_packages_cm_bind_address }}'
  notify:
    - Enable and Start CodeMeter Systemd Service
