---
- name: Install AxProtector in the requested version
  ansible.builtin.apt:
    name: "{{ package_name }}{{ ('=' + package_version) if package_version else '' }}"
    state: present
    allow_downgrade: '{{ wibu_packages_allow_downgrades }}'
