galaxy_info:
  role_name: grub_config
  namespace: voraus
  author: Jan-Frederik Schmidt
  description: >
    Configures GRUB config entries.
  company: voraus robotik GmbH
  license: MIT

  min_ansible_version: '2.1'

  galaxy_tags: []

dependencies: []
