---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    force: true
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: example-test
    box: debian/bookworm64
    memory: 1024
    cpus: 4
    provider_raw_config_args:
      - "nic_model_type = 'e1000'" # Required for IRQ management, virtio interfaces to not have IRQ threads
    networks:
      - name: 'public_network'
        type: 'dhcp'
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        core_isolation_isolated_core_ids: [1, 3]
    host_vars:
      example-test:
        core_isolation_isolated_network_interfaces:
          eth0: 1
        expected_cmdline_params:
          irqaffinity: '0,2'
          isolcpus: 'managed_irq,domain,1,3'
          rcu_nocbs: '1,3'
          rcu_nocb_poll:
          nomodeset:
        expected_environment_variables:
          - VRT_COREISOLATION__IDS=[1,3]
          - VRT_INTERFACE_PINNING__eth0=[1]
  playbooks:
    converge: ../../voraus/ipc_tools/playbooks/example.yml
verifier:
  name: testinfra
  options:
    # https://github.com/pytest-dev/pytest-testinfra/issues/58#issuecomment-1839460327
    # pytest-ansible conflicts with --connection
    p: 'no:pytest-ansible'

    # avoid loading global pyproject.toml options, so we don't
    # load the setting that says "disable testinfra"
    c: '.'

    sudo: true # /boot/grub/grub.cfg is only readable by root
